@startuml C1_Register_ShippingAgents_Scenario_View
title C1 — Contexto | Vista de Cenários — UC: Register Shipping Agent Organization

actor "Port Authority Officer" as PortOfficer
actor "Shipping Agent Representative" as Rep

rectangle "Port Logistics Management System (PLMS)" as PLMS {
  usecase "Register Shipping Agent Organization" as UC_Register
}

Rep --> UC_Register
PortOfficer --> UC_Register

@enduml
