@startuml C1 - Process View (US Register Shipping Agent Organizations)
!include <C4/C4_Container>

Person(portOfficer, "Port Authority Officer")
System(api, "Port API")

portOfficer -> api : 1. POST /api/ShippingAgents\n(CreateShippingAgentDTO)
api --> portOfficer : 2. 201 Created (ShippingAgentDTO)

portOfficer -> api : 3. GET /api/ShippingAgents/{taxNumber}
api --> portOfficer : 4. 200 OK (ShippingAgentDTO)

@enduml