@startuml C4_Register_Shipping_Agents_Implementation_View
title C4 – Register Shipping Agents (Implementation / Package View – Shipping Organizations)
left to right direction
hide empty members

skinparam package {
  BackgroundColor White
  BorderColor Black
  FontColor Black
}
skinparam arrow {
  Color Black
}

package "Controllers.ShippingOrganizations" {
  [ShippingAgentsController]
}

package "Application.Services.ShippingOrganizations" {
  [ShippingAgentService]
}

package "Application.Mapping" {
  [ShippingAgentMapper]
}

package "Domain.Repositories" {
  [IShippingAgentRepository]
}

package "Models.ShippingOrganizations" {
  [ShippingAgent]
  [ShippingAgentDTO]
  [CreateShippingAgentDTO]
  [Address]
  [Representative]
  [ShippingAgentType]
}

package "Infrastructure.Data" {
  [PortContext]
}


[ShippingAgentsController] --> [ShippingAgentService]
[ShippingAgentService] --> [ShippingAgentMapper]
[ShippingAgentService] --> [IShippingAgentRepository]
[IShippingAgentRepository] --> [PortContext]

[ShippingAgentMapper] --> [ShippingAgent]
[ShippingAgentMapper] --> [ShippingAgentDTO]
[ShippingAgentMapper] --> [CreateShippingAgentDTO]


[ShippingAgent] --> [ShippingAgentType] : uses

[ShippingAgent] --> [Address]
[ShippingAgent] --> [Representative]
@enduml
