@startuml C4_Register_Shipping_Agents_Logical_View
title C4 — Código | Vista Lógica — Shipping Agents Management API (componentes/classes)
left to right direction
hide empty members

skinparam package { 
  BackgroundColor White;
   BorderColor Black; 
   FontColor Black; 
   FontStyle bold
    }
skinparam class   { 
  BackgroundColor White; 
  BorderColor Black; 
  FontColor Black 
  }

package "Controllers.ShippingOrganizations" {
  class ShippingAgentsController {
    + Post(dto: CreateShippingAgentDTO) : ActionResult<ShippingAgentDTO>
    + GetByTaxNumber(taxNumber: long) : ActionResult<ShippingAgentDTO>
  }
}

package "Application.Services.ShippingOrganizations" {
  class ShippingAgentService {
    + RegisterAsync(dto: CreateShippingAgentDTO) : Task<ShippingAgentDTO>
    + GetByTaxNumberAsync(taxNumber: long) : Task<ShippingAgentDTO?>
    - _repo : IShippingAgentRepository
    - _mapper : ShippingAgentMapper
  }
}

package "Application.Mapping" {
  class ShippingAgentMapper {
    + ToDomain(dto: CreateShippingAgentDTO) : ShippingAgent
    + ToDTO(model: ShippingAgent) : ShippingAgentDTO
  }
}

package "Domain.Repositories" {
  interface IShippingAgentRepository {
    + ExistsByTaxNumberAsync(taxNumber: long) : Task<bool>
    + AddAsync(agent: ShippingAgent) : Task
    + GetByTaxNumberAsync(taxNumber: long, includeRepresentatives: bool = false) : Task<ShippingAgent?>
    + SaveChangesAsync() : Task
  }
}

package "Models.ShippingOrganizations" {
  class ShippingAgent {
    + TaxNumber : long
    + LegalName : string
    + AlternativeName : string
    + Type : ShippingAgentType
    + Address : Address
    + Representatives : List<Representative>
  }
  class ShippingAgentType <<Value Object>> { 
    + Value : string
     }
  class Address <<Value Object>> {
     + Street : string;
    + City : string;
     + PostalCode : string; 
     + Country : string 
     }
  class Representative { 
    + Name : string; 
    + CitizenID : string; 
    + Nationality : string; 
    + PhoneNumber : string
     }

  class ShippingAgentDTO { 
    + ... 
    }
  class CreateShippingAgentDTO { 
    + ... 
    }
}

package "Infrastructure.Data" {
  class PortContext <<DbContext>> { 
    + ShippingAgents : DbSet<ShippingAgent> 
    }
  class EfShippingAgentRepository <<implements IShippingAgentRepository>> { 
    - _ctx : PortContext 
    }
}

' Relações (lógicas)
ShippingAgentsController --> ShippingAgentService
ShippingAgentService --> ShippingAgentMapper
ShippingAgentService --> IShippingAgentRepository
EfShippingAgentRepository -up-|> IShippingAgentRepository
EfShippingAgentRepository --> PortContext

ShippingAgentMapper --> ShippingAgent
ShippingAgentMapper --> ShippingAgentDTO
ShippingAgentMapper --> CreateShippingAgentDTO

ShippingAgent --> ShippingAgentType
ShippingAgent *-- Address
ShippingAgent *-- Representative
@enduml
