@startuml C2_impl
title C2 — Containers (implementação) — Storage Areas

node "Client" as Client {
  component "Port Ops Web UI\n(React/Swagger/Postman)" as Web
}

node "Port Operations API\nASP.NET Core" as Api {
  component "StorageAreasController\n(Web API)" as Ctrl
  component "StorageAreaService\n(Application)" as App
  component "StorageAreaMapper/DTOs" as Map
}

node "Persistence\nEF Core" as Persistence {
  component "EfStorageAreaRepository\n(IStorageAreaRepository)" as AreaRepo
  component "EfDockRepository\n(IDockRepository)" as DockRepo
  database "PortContext\n(SQL DB)" as DB
}

Client --> Ctrl : HTTP/JSON
Ctrl --> App
App --> AreaRepo
App --> DockRepo : valida docks servidos
AreaRepo --> DB
DockRepo --> DB
App --> Map
@enduml
