@startuml C1_Cenario
title C1 — Contexto do Sistema (US 2.2.3 - Docks)

actor "Port Authority Officer" as Officer
rectangle "Port Operations API\n(TodoApi)" as System {
}

cloud "Identity Provider\n(AuthN/AuthZ)" as IdP
rectangle "Port Ops Web UI\n(Swagger/Postman/SPA)" as WebUI

Officer --> WebUI : usa
WebUI --> System : HTTP/REST
Officer --> System : (alternativo) chama REST direto
System .. IdP : valida tokens (opcional/futuro)

note bottom of System
- Objetivo: registar/atualizar docks
- Expor consulta/filtragem
end note
@enduml
