@startuml C1_Logica
title C1 — Lógica de Contexto

skinparam rectangle {
  BackgroundColor<<Boundary>> #EEF
  BorderColor<<Boundary>> #66A
}

actor "Port Authority Officer" as Officer
rectangle "Port Ops Web UI" as WebUI <<Boundary>>
rectangle "Port Operations API\n(TodoApi)" as API <<Boundary>>

Officer --> WebUI : CRUD Docks
WebUI --> API : REST/JSON
API : Registo/Atualização/Pesquisa\nValidação mínima\nMapeamento DTO<->Modelo
@enduml
