@startuml C1_Processos
title C1 — Processos (high level)

start
:Officer escolhe ação;

partition "Criar Dock" {
  :Preenche Name/Location/\nLength/Depth/MaxDraft;\nSeleciona VesselTypes;
  :POST /api/Docks;
  if (IDs VesselType válidos?) then (sim)
    :201 Created;
  else (não)
    :400 Bad Request;
  endif
}

partition "Atualizar Dock" {
  :PUT /api/Docks/{id} com UpdateDockDTO;
  if (id == dto.Id?) then (sim)
    :204 No Content;
  else (não)
    :400 ID mismatch;
  endif
}

partition "Pesquisar/Filtrar" {
  :GET /api/Docks?name&vesselTypeId&location;
  :200 OK [DockDTO...];
}
stop
@enduml
