@startuml C2_impl
title C2 — Containers (implementação)

node "Client" as Client {
  component "Port Ops Web UI\n(React/Swagger/Postman)" as Web
}

node "Port Operations API\nASP.NET Core" as Api {
  component "DocksController\n(Web API)" as Ctrl
  component "DockService\n(Application)" as App
  component "DockMapper/DTOs" as Map
}

node "Persistence\nEF Core" as Persistence {
  component "EfDockRepository\n(IDockRepository)" as DockRepo
  component "IVesselTypeRepository" as VTRepo
  database "PortContext\n(SQL DB)" as DB
}

Client --> Ctrl : HTTP/JSON
Ctrl --> App
App --> DockRepo
App --> VTRepo
DockRepo --> DB
VTRepo --> DB
App --> Map

@enduml
