@startuml C2_Logica
title C2 — Lógica entre Containers

rectangle API {
  [Controller] --> [Service]
  [Service] --> [Mapper/DTO]
}
rectangle Persistence {
  [Service] --> [DockRepository]
  [Service] --> [VesselTypeRepository]
  [DockRepository] --> [DB]
  [VesselTypeRepository] --> [DB]
}
actor Officer
Officer --> [Controller] : REST calls

@enduml
