@startuml C3_impl
title C3 — Componentes internos (Docks)

package "TodoApi.Controllers.Docks" {
  component "DocksController"
}

package "TodoApi.Application.Services.Docks" {
  interface "IDockService"
  component "DockService"
}

package "TodoApi.Domain.Repositories" {
  interface "IDockRepository"
  interface "IVesselTypeRepository"
}

package "TodoApi.Infrastructure.Repositories" {
  component "EfDockRepository"
}

package "TodoApi.Models.Docks" {
  class Dock
  class CreateDockDTO
  class UpdateDockDTO
  class DockDTO
  class DockMapper <<static>>
}

package "TodoApi.Models.Vessels" {
  class VesselType
  class VesselTypeDTO
}

DocksController --> IDockService
DockService ..|> IDockService
DockService --> IDockRepository
DockService --> IVesselTypeRepository
EfDockRepository ..|> IDockRepository

DockService --> DockMapper
DockMapper --> DockDTO
Dock --> "0..*" VesselType
DockMapper --> VesselTypeDTO

@enduml
