@startuml C4_Logica
title C4 — Camadas Lógicas

package Controllers {
  [DocksController]
}
package Application {
  [DockService]
  [IDockService]
}
package Domain {
  [Dock]
  [VesselType]
  [IDockRepository]
  [IVesselTypeRepository]
}
package Infrastructure {
  [EfDockRepository]
  [PortContext / EF Core]
}
package DTOs_&_Mappers {
  [CreateDockDTO]
  [UpdateDockDTO]
  [DockDTO]
  [VesselTypeDTO]
  [DockMapper]
}

[DocksController] --> [IDockService]
[DockService] ..> [IDockRepository]
[DockService] ..> [IVesselTypeRepository]
[DockService] ..> [DockMapper]
[EfDockRepository] ..> [PortContext / EF Core]
[DockMapper] ..> [DockDTO]

@enduml
