@startuml C4_Processos
title C4 — Sequência detalhada (GetDocks com filtros)

actor Client
participant Controller as "DocksController"
participant Service as "DockService"
participant Repo as "EfDockRepository"
database DB as "PortContext/DB"

Client -> Controller: GET /api/Docks?name&vesselTypeId&location
Controller -> Service: GetDocksAsync(name, vesselTypeId, location)
Service -> Repo: GetAllAsync(name, vesselTypeId, location)
Repo -> DB: SELECT Docks\nINCLUDE AllowedVesselTypes\nWHERE name LIKE, location LIKE\nAND EXISTS vtId (opcional)
DB --> Repo: IEnumerable<Dock>
Repo --> Service: IEnumerable<Dock>
Service -> Service: mapear Dock -> DockDTO
Service --> Controller: IEnumerable<DockDTO>
Controller --> Client: 200 OK [DockDTO...]

@enduml
