@startuml US_3_1_2_C2_Logica
title US 3.1.2 - Lógica do layout

rectangle "LayoutComponent" {
  [Header]
  [Nav (Menu)]
  [Breadcrumbs]
  [Content router-outlet]
  [Footer]
}

[Header] --> [Lang Switch]
[Header] --> [Logo+Title]
[Header] --> [User Info + Logout]
[Nav (Menu)] --> [Menu Items por role]
[Content router-outlet] --> [Feature Pages]

@enduml
