@startuml C1_Create_Vessel_Visit_Execution_Process_View
title C1 – Create Vessel Visit Execution (Process View)

actor "Logistics Operator" as LogisticsOp
participant "OEM API\n(NestJS)" as Controller
participant "VVEService" as Service
participant "Repository\n(TypeORM)" as Context
database "Database" as DB


LogisticsOp -> Controller : POST /oem/vessel-visit-executions\n(vvnId, actualArrivalTime)
Controller -> Service : createExecution(payload, user)
Service -> Context : Valida VVN e cria VVE
Service -> Service : Gera identifier\nDefine status: in-progress\nCaptura createdBy
Context -> DB : INSERT vessel_visit_executions
DB --> Context : Confirm
Service --> Controller : VVE criado
Controller --> LogisticsOp : HTTP 201 Created\n(VesselVisitExecutionEntity)

@enduml
