// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Models;

#nullable disable

namespace TodoApi.Migrations
{
    [DbContext(typeof(PortContext))]
    partial class PortContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TodoApi.Models.Auth.ActivationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RedeemedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedeemedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ActivationTokens", (string)null);
                });

            modelBuilder.Entity("TodoApi.Models.Auth.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Email = "admin@example.com",
                            Name = "Local Admin"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Email = "salvadordevlapr@gmail.com",
                            Name = "Salvador DevLapr"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Email = "portauthoritylapr5@gmail.com",
                            Name = "Port Authority LAPR5"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Name = "ExternalIamProvider"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Name = "PortAuthorityOfficer"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Name = "ShippingAgentRepresentative"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Name = "LogisticsOperator"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Name = "SystemUser"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Auth.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Docks.Dock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Depth")
                        .HasColumnType("REAL");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxDraft")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Docks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Depth = 15.0,
                            Length = 300.0,
                            Location = "North Side",
                            MaxDraft = 12.0,
                            Name = "North Pier 1"
                        },
                        new
                        {
                            Id = 2L,
                            Depth = 12.0,
                            Length = 250.0,
                            Location = "East Side",
                            MaxDraft = 10.0,
                            Name = "East Dock A"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.PublicResources.ResourceAccessLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResourceAccessLogs", (string)null);
                });

            modelBuilder.Entity("TodoApi.Models.PublicResources.SharedResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiskPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SharedResources", (string)null);
                });

            modelBuilder.Entity("TodoApi.Models.Qualifications.Qualification", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Qualifications", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "STS_OP",
                            Description = "STS Crane Operator"
                        },
                        new
                        {
                            Code = "TRUCK_DRV",
                            Description = "Truck Driver"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Resources.Resource", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedArea")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OperationalCapacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SetupTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Resources", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "CRANE_01",
                            AssignedArea = "Dock 1",
                            Description = "STS Crane 01",
                            OperationalCapacity = 50.0m,
                            SetupTimeMinutes = 30,
                            Status = "Active",
                            Type = "Crane"
                        },
                        new
                        {
                            Code = "TRUCK_01",
                            AssignedArea = "Yard A",
                            Description = "Yard Truck 01",
                            OperationalCapacity = 20.0m,
                            SetupTimeMinutes = 15,
                            Status = "Active",
                            Type = "Truck"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.ShippingOrganizations.ShippingAgent", b =>
                {
                    b.Property<long>("TaxNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternativeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("TaxNumber");

                    b.ToTable("ShippingAgents");

                    b.HasData(
                        new
                        {
                            TaxNumber = 500123456L,
                            AlternativeName = "Acme",
                            LegalName = "Acme Shipping S.A.",
                            Type = "Owner"
                        },
                        new
                        {
                            TaxNumber = 500123457L,
                            AlternativeName = "BlueOcean",
                            LegalName = "Blue Ocean Lda",
                            Type = "Operator"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Staff.StaffMember", b =>
                {
                    b.Property<string>("MecanographicNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MecanographicNumber");

                    b.ToTable("StaffMembers", (string)null);
                });

            modelBuilder.Entity("TodoApi.Models.StorageAreas.StorageArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentOccupancyTEU")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DockDistances")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCapacityTEU")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServedDockIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StorageAreas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentOccupancyTEU = 200,
                            DockDistances = "{}",
                            Location = "North Yard",
                            MaxCapacityTEU = 1000,
                            ServedDockIds = "[]",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CurrentOccupancyTEU = 120,
                            DockDistances = "{}",
                            Location = "East Warehouse",
                            MaxCapacityTEU = 500,
                            ServedDockIds = "[]",
                            Type = 1
                        });
                });

            modelBuilder.Entity("TodoApi.Models.VesselVisitNotifications.ContainerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CargoType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsForUnloading")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VesselVisitNotificationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VesselVisitNotificationId");

                    b.ToTable("ContainerItem");
                });

            modelBuilder.Entity("TodoApi.Models.VesselVisitNotifications.CrewMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("VesselVisitNotificationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VesselVisitNotificationId");

                    b.ToTable("CrewMember");
                });

            modelBuilder.Entity("TodoApi.Models.VesselVisitNotifications.VesselVisitNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ApprovedDockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecisionTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OfficerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmissionTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedByRepresentativeEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedByRepresentativeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VesselVisitNotifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AgentId = 1L,
                            ArrivalDate = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            VesselId = "1234567"
                        },
                        new
                        {
                            Id = 2L,
                            AgentId = 2L,
                            ArrivalDate = new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            VesselId = "7654321"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Vessels.Vessel", b =>
                {
                    b.Property<string>("Imo")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("VesselTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Imo");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("Vessels", (string)null);

                    b.HasData(
                        new
                        {
                            Imo = "1234567",
                            Name = "MV Example One",
                            Operator = "Example Shipping Co",
                            VesselTypeId = 1L
                        },
                        new
                        {
                            Imo = "7654321",
                            Name = "MT Sample Tanker",
                            Operator = "Tankers Ltd",
                            VesselTypeId = 2L
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Vessels.VesselType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DockId");

                    b.ToTable("VesselTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Capacity = 50000,
                            Description = "Large cargo ship for containers",
                            Name = "Container Ship"
                        },
                        new
                        {
                            Id = 2L,
                            Capacity = 120000,
                            Description = "Carries liquids and oils",
                            Name = "Tanker"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Auth.ActivationToken", b =>
                {
                    b.HasOne("TodoApi.Models.Auth.AppUser", "AppUser")
                        .WithMany("ActivationTokens")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("TodoApi.Models.Auth.UserRole", b =>
                {
                    b.HasOne("TodoApi.Models.Auth.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoApi.Models.Auth.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TodoApi.Models.Resources.Resource", b =>
                {
                    b.OwnsMany("TodoApi.Models.Resources.ResourceQualification", "RequiredQualifications", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("QualificationCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("QualificationCode");

                            b1.Property<string>("ResourceCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ResourceCode");

                            b1.ToTable("ResourceQualifications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResourceCode");
                        });

                    b.Navigation("RequiredQualifications");
                });

            modelBuilder.Entity("TodoApi.Models.ShippingOrganizations.ShippingAgent", b =>
                {
                    b.OwnsMany("TodoApi.Models.Representatives.Representative", "Representatives", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CitizenID")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT");

                            b1.Property<long>("ShippingAgentTaxNumber")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("ShippingAgentTaxNumber");

                            b1.ToTable("Representative");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentTaxNumber");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    CitizenID = "C12345",
                                    Email = "joao.silva@acme.com",
                                    IsActive = true,
                                    Name = "João Silva",
                                    Nationality = "PT",
                                    PhoneNumber = "+351900000000",
                                    ShippingAgentTaxNumber = 500123456L
                                },
                                new
                                {
                                    Id = 2,
                                    CitizenID = "C12346",
                                    Email = "maria.costa@acme.com",
                                    IsActive = true,
                                    Name = "Maria Costa",
                                    Nationality = "PT",
                                    PhoneNumber = "+351911111111",
                                    ShippingAgentTaxNumber = 500123456L
                                },
                                new
                                {
                                    Id = 3,
                                    CitizenID = "C22345",
                                    Email = "pedro.azul@blueocean.com",
                                    IsActive = true,
                                    Name = "Pedro Azul",
                                    Nationality = "PT",
                                    PhoneNumber = "+351922222222",
                                    ShippingAgentTaxNumber = 500123457L
                                });
                        });

                    b.OwnsOne("TodoApi.Models.ShippingOrganizations.Address", "Address", b1 =>
                        {
                            b1.Property<long>("ShippingAgentTaxNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("ShippingAgentTaxNumber");

                            b1.ToTable("ShippingAgents");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentTaxNumber");

                            b1.HasData(
                                new
                                {
                                    ShippingAgentTaxNumber = 500123456L,
                                    City = "Porto",
                                    Country = "PT",
                                    PostalCode = "4000-000",
                                    Street = "Rua A"
                                },
                                new
                                {
                                    ShippingAgentTaxNumber = 500123457L,
                                    City = "Lisboa",
                                    Country = "PT",
                                    PostalCode = "1000-000",
                                    Street = "Avenida B"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Representatives");
                });

            modelBuilder.Entity("TodoApi.Models.Staff.StaffMember", b =>
                {
                    b.OwnsMany("TodoApi.Models.Staff.StaffQualification", "Qualifications", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("QualificationCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("QualificationCode");

                            b1.Property<string>("StaffMecanographicNumber")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("StaffMecanographicNumber");

                            b1.ToTable("StaffQualifications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StaffMecanographicNumber");
                        });

                    b.OwnsOne("TodoApi.Models.Staff.OperationalWindow", "OperationalWindow", b1 =>
                        {
                            b1.Property<string>("StaffMemberMecanographicNumber")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("EndTime");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("StartTime");

                            b1.HasKey("StaffMemberMecanographicNumber");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberMecanographicNumber");
                        });

                    b.Navigation("OperationalWindow");

                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("TodoApi.Models.VesselVisitNotifications.ContainerItem", b =>
                {
                    b.HasOne("TodoApi.Models.VesselVisitNotifications.VesselVisitNotification", null)
                        .WithMany("CargoManifest")
                        .HasForeignKey("VesselVisitNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoApi.Models.VesselVisitNotifications.CrewMember", b =>
                {
                    b.HasOne("TodoApi.Models.VesselVisitNotifications.VesselVisitNotification", null)
                        .WithMany("CrewMembers")
                        .HasForeignKey("VesselVisitNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoApi.Models.Vessels.Vessel", b =>
                {
                    b.HasOne("TodoApi.Models.Vessels.VesselType", "VesselType")
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VesselType");
                });

            modelBuilder.Entity("TodoApi.Models.Vessels.VesselType", b =>
                {
                    b.HasOne("TodoApi.Models.Docks.Dock", null)
                        .WithMany("AllowedVesselTypes")
                        .HasForeignKey("DockId");

                    b.OwnsOne("TodoApi.Models.Vessels.ValueObjects.OperationalConstraints", "OperationalConstraints", b1 =>
                        {
                            b1.Property<long>("VesselTypeId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxBays")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxBays");

                            b1.Property<int>("MaxRows")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxRows");

                            b1.Property<int>("MaxTiers")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxTiers");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");

                            b1.HasData(
                                new
                                {
                                    VesselTypeId = 1L,
                                    MaxBays = 20,
                                    MaxRows = 12,
                                    MaxTiers = 8
                                },
                                new
                                {
                                    VesselTypeId = 2L,
                                    MaxBays = 25,
                                    MaxRows = 15,
                                    MaxTiers = 9
                                });
                        });

                    b.Navigation("OperationalConstraints")
                        .IsRequired();
                });

            modelBuilder.Entity("TodoApi.Models.Auth.AppUser", b =>
                {
                    b.Navigation("ActivationTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TodoApi.Models.Docks.Dock", b =>
                {
                    b.Navigation("AllowedVesselTypes");
                });

            modelBuilder.Entity("TodoApi.Models.VesselVisitNotifications.VesselVisitNotification", b =>
                {
                    b.Navigation("CargoManifest");

                    b.Navigation("CrewMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
