@startuml domain_model
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

top to bottom direction

package "VesselAggregate" {

  class VesselRecord <<AggregateRoot>> <<Entity>> { }

  class IMOnumber <<ValueObject>> { }
  class VesselName <<ValueObject>> { }
  class VesselRows <<ValueObject>> { }
  class VesselBays <<ValueObject>> { }
  class VesselTiers <<ValueObject>> { }

  VesselRecord "1"-- "1" IMOnumber: has >
  VesselRecord "1"-- "1" VesselName: has >
  VesselRecord "1"-- "1" VesselRows: has >
  VesselRecord "1"-- "1" VesselBays: has >
  VesselRecord "1"-- "1" VesselTiers: has >
  VesselRecord "1"-- "1" VesselTypeId: has >
}

package "VesselTypeAggregate" {
  class VesselType <<AggregateRoot>> <<Entity>> { }
  class VesselTypeId <<ValueObject>> { }
  class TypeName <<ValueObject>> { }
  class TypeDescription <<ValueObject>> { }
  class Capacity <<ValueObject>> { }
  class MaxRows <<ValueObject>> { }
  class MaxBays <<ValueObject>> { }
  class MaxTiers <<ValueObject>> { }

  VesselType "1"-- "1" VesselTypeId: has >
  VesselType "1"-- "1" TypeName: has >
  VesselType "1"-- "0..*" TypeDescription: has >
  VesselType "1"-- "1" Capacity: has >
  VesselType "1"-- "1" MaxRows: has >
  VesselType "1"-- "1" MaxBays: has >
  VesselType "1"-- "1" MaxTiers: has >
}

package "VesselVisitAggregate" {
  class VesselVisitNotification <<AggregateRoot>> <<Entity>> { }

  class VisitID <<ValueObject>> { }
  class ScheduledArrival <<ValueObject>> { }
  class ScheduledDeparture <<ValueObject>> { }

  class Status <<ValueObject>> {
    Pending
    Rejected
    Approved
    Completed
  }

  class CrewInfo <<ValueObject>> {
    crewCaptain
    crewSize
  }
}

package "CargoManifestAggregate" {
  class CargoManifest <<AggregateRoot>> <<Entity>> { }

  class ManifestType <<ValueObject>> {
    Loading
    Unloading
  }

  class ManifestID <<ValueObject>> { }
  class ManifestWeight <<ValueObject>> { }

  class ManifestEntry <<Entity>> { }
  class EntryNumber <<ValueObject>> { }
  class EntryWeight <<ValueObject>> { }

  class EntryPosition <<ValueObject>> {
    bay
    row
    tier
  }

  class DestinationOrCurrentLocation <<ValueObject>> { }

  class CargoType <<ValueObject>> {
    HAZMAT
    RefrigeratedGoods
    GeneralConsumerProducts
    Electronics
    OversizedIndustrialEquipment
  }

  class Container <<Entity>> { }
  class IsoID <<ValueObject>> { }
  class ContainerSize <<ValueObject>> { }
  class ContainerWeight <<ValueObject>> { }

  CargoManifest "1"-- "1" ManifestID: has >
  CargoManifest "1"-- "1" ManifestType: has >
  CargoManifest "1"-- "0..1" ManifestWeight: has >
  CargoManifest "1" -- "1..*" ManifestEntry : includes >
}

package "StaffAggregate" {
  class StaffMember <<AggregateRoot>> <<Entity>> { }

  class StaffID <<ValueObject>> { }
  class StaffName <<ValueObject>> { }

  class ContactInfo <<ValueObject>> {
    email
    phoneNumber
  }

  class OperationalWindow <<ValueObject>> {
    startTime
    endTime
  }

  class StaffStatus <<ValueObject>> {
    Available
    Unavailable
  }

  StaffMember "1"-- "1" StaffID: has >
  StaffMember "1"-- "1" StaffName: has >
  StaffMember "1"-- "1" ContactInfo: has >
  StaffMember "1"-- "1" OperationalWindow: has >
  StaffMember "1"-- "1" StaffStatus: has >
}

package "QualificationAggregate" {
  class Qualification <<AggregateRoot>> <<Entity>> { }

  class QualificationCode <<ValueObject>> { }
  class QualificationDescription <<ValueObject>> { }

  Qualification "1"-- "1" QualificationCode: has >
  Qualification "1"-- "0..*" QualificationDescription: has >
}

package "ResourceAggregate" {
  class Resource <<AggregateRoot>> <<Entity>> { }

  class ResourceID <<ValueObject>> { }
  class ResourceDescription <<ValueObject>> { }
  class OperationalCapacity <<ValueObject>> { }

  class AvailabilityStatus <<ValueObject>> {
    Active
    Inactive
    UnderMaintenance
  }

  class ResourceType <<ValueObject>> {
    MobileCrane
    FixedCrane
    Truck
  }

  Resource "1" -- "1" ResourceID: has >
  Resource "1" -- "1" ResourceDescription: has >
  Resource "1" -- "1" OperationalCapacity: has >
  Resource "1" -- "1" AvailabilityStatus: has >
  Resource "1" -- "1" ResourceType: has >
}

package "DockAggregate" {
  class Dock <<AggregateRoot>> <<Entity>> { }

  class DockID <<ValueObject>> { }
  class DockName <<ValueObject>> { }
  class Location <<ValueObject>> { }
  class Length <<ValueObject>> { }
  class Depth <<ValueObject>> { }
  class MaxDraft <<ValueObject>> { }

  class AllowedVesselType <<Entity>> {
    vesselTypeId : VesselTypeId
  }

  Dock "1" -- "1" DockID: has >
  Dock "1" -- "1" DockName: has >
  Dock "1" -- "1" Location: has >
  Dock "1" -- "1" Length: has >
  Dock "1" -- "1" Depth: has >
  Dock "1" -- "1" MaxDraft: has >

  Dock "1" -- "0..*" AllowedVesselType : allows >
}

package "StorageAreaAggregate" {
  class StorageArea <<AggregateRoot>> <<Entity>> { }

  class StorageAreaID <<ValueObject>> { }
  class StorageAreaType <<ValueObject>> {
    Yard
    Warehouse
  }
  class StorageLocation <<ValueObject>> { }
  class StorageAreaCapacity <<ValueObject>> { }
  class CurrentUtilization <<ValueObject>> { }

  StorageArea "1" -- "1" StorageAreaID: has >
  StorageArea "1" -- "1" StorageAreaType: has >
  StorageArea "1" -- "1" StorageLocation: has >
  StorageArea "1" -- "1" StorageAreaCapacity: has >
  StorageArea "1" -- "1" CurrentUtilization: has >
}

package "ShippingOrganizationAggregate" {
  class ShippingAgent <<AggregateRoot>> <<Entity>> { }

  class ShippingAgentName <<ValueObject>> { }
  class TaxNumber <<ValueObject>> { }
  class ShippingAgentType <<ValueObject>> {
    Owner
    Operator
  }
  class Address <<ValueObject>> {
    street
    city
    postalCode
    country
  }

  class Representative <<Entity>> { }
  class RepresentativeName <<ValueObject>> { }
  class RepresentativeCitizenID <<ValueObject>> { }
  class RepresentativeNationality <<ValueObject>> { }
  class RepresentativeEmail <<ValueObject>> { }
  class RepresentativePhoneNumber <<ValueObject>> { }

  ShippingAgent "1" -- "1" ShippingAgentName: has >
  ShippingAgent "1" -- "1" TaxNumber: has >
  ShippingAgent "1" -- "1" ShippingAgentType: has >
  ShippingAgent "1" -- "1" Address: has >

  Representative "1" -- "1" RepresentativeName: has >
  Representative "1" -- "1" RepresentativeCitizenID: has >
  Representative "1" -- "1" RepresentativeNationality: has >
  Representative "1" -- "1" RepresentativeEmail: has >
  Representative "1" -- "1" RepresentativePhoneNumber: has >
}

StorageArea "0..*" -- "0..*" Dock : may serve >
StaffMember "0..*" -- "0..*" Qualification : possesses >
Resource "0..*" -- "0..1" Dock : may be located at >
Resource "0..*" -- "0..1" StorageArea : may be assigned to >
Resource "0..*" -- "0..*" Qualification : requires >
ShippingAgent "1" -- "0..*" Representative : employs >
ShippingAgent "1" -- "0..*" VesselRecord : represents >
ShippingAgent "1" -- "0..*" VesselVisitNotification : submits >
CargoManifest "1" -- "1..*" ManifestEntry : includes >
ManifestEntry "1" -- "1" EntryNumber : has >
ManifestEntry "1" -- "1" EntryPosition : has >
ManifestEntry "1" -- "1" DestinationOrCurrentLocation : has >
ManifestEntry "1" -- "1" CargoType : has >
ManifestEntry "1" -- "1" EntryWeight : has >
ManifestEntry "1" -- "1" Container : includes >
Container "1" -- "1" IsoID : has >
Container "1" -- "1" ContainerSize : has >
Container "1" -- "1" ContainerWeight : has >
VesselVisitNotification "1" -- "1" VisitID : has >
VesselVisitNotification "1" -- "1" ScheduledArrival : has >
VesselVisitNotification "1" -- "1" ScheduledDeparture : has >
VesselVisitNotification "1" -- "1" Status : has >
VesselVisitNotification "1" -- "1" CrewInfo : has >
VesselVisitNotification "1" -- "1" VesselRecord : for >
VesselVisitNotification "1" -- "0..*" CargoManifest : has >
VesselVisitNotification "0..1" -- "1" Dock : assigned to >
VesselVisitNotification "0..*" -- "0..*" Resource : requires >
AllowedVesselType ..> VesselType : references >
VesselRecord ..> VesselType : references >

@enduml
