server {
    listen 80;
    server_name _;

    # SPA estática (Angular)
    root /usr/share/nginx/html;
    index index.html;

    # Fallback para client-side routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}
